export interface Driver {
    id?: number; // Optional for when creating a new driver, as the ID is generated by the backend
    driverName: string;
    driverEmail: string;
    driverMobile: string;
    requestDate?: Date; // Optional, managed by the backend
    requestStatus?: string; // You might use an enum or string here, depending on how you want to handle it in the frontend
    videoConferenceMeetingDate?: Date; // This can be null/optional
    notesToRequester?: string;
    emailSent?: boolean;
  }
  